-- =============================================================================
-- V202609010030__Logistics_Analytics_Service__Init.sql
-- Kinara OS — Logistics Analytics Service
-- =============================================================================
\c kinara_logistics_analytics;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- delivery_metrics
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS delivery_metrics (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    metric_date         DATE        NOT NULL,
    country             TEXT        NOT NULL,
    region              TEXT,
    total_shipments     INT         DEFAULT 0,
    delivered_count     INT         DEFAULT 0,
    failed_count        INT         DEFAULT 0,
    avg_delivery_hours  NUMERIC(8,2),
    on_time_pct         NUMERIC(5,2),
    total_revenue_usd   NUMERIC(14,4),
    calculated_at       TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE delivery_metrics IS 'Daily aggregated delivery performance metrics rolled up by country and region';
COMMENT ON COLUMN delivery_metrics.metric_date        IS 'Calendar date the metrics represent';
COMMENT ON COLUMN delivery_metrics.total_shipments    IS 'Total shipments dispatched on this date in this region';
COMMENT ON COLUMN delivery_metrics.delivered_count    IS 'Shipments successfully delivered on this date';
COMMENT ON COLUMN delivery_metrics.failed_count       IS 'Shipments that failed, were returned, or lost on this date';
COMMENT ON COLUMN delivery_metrics.avg_delivery_hours IS 'Mean time from collection to delivery in hours';
COMMENT ON COLUMN delivery_metrics.on_time_pct        IS 'Percentage of deliveries completed within the SLA window';
COMMENT ON COLUMN delivery_metrics.total_revenue_usd  IS 'Total freight revenue for this date and region in USD equivalent';
COMMENT ON COLUMN delivery_metrics.calculated_at      IS 'Timestamp when this metric row was last computed or updated';

-- ---------------------------------------------------------------------------
-- vehicle_utilization
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vehicle_utilization (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    metric_date      DATE        NOT NULL,
    vehicle_id       UUID        NOT NULL,
    total_trips      INT         DEFAULT 0,
    distance_km      NUMERIC(10,3) DEFAULT 0,
    revenue_usd      NUMERIC(12,4) DEFAULT 0,
    fuel_cost_usd    NUMERIC(10,4) DEFAULT 0,
    utilization_pct  NUMERIC(5,2) DEFAULT 0,
    calculated_at    TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE vehicle_utilization IS 'Daily vehicle utilisation and cost metrics for fleet performance tracking';
COMMENT ON COLUMN vehicle_utilization.vehicle_id      IS 'Cross-DB reference to vehicles.id in kinara_fleet';
COMMENT ON COLUMN vehicle_utilization.total_trips     IS 'Number of completed delivery trips by this vehicle on this date';
COMMENT ON COLUMN vehicle_utilization.distance_km     IS 'Total kilometres driven by this vehicle on this date';
COMMENT ON COLUMN vehicle_utilization.revenue_usd     IS 'Revenue generated by this vehicle on this date in USD equivalent';
COMMENT ON COLUMN vehicle_utilization.fuel_cost_usd   IS 'Estimated or actual fuel expenditure in USD equivalent';
COMMENT ON COLUMN vehicle_utilization.utilization_pct IS 'Percentage of available hours the vehicle was actively in use';

-- ---------------------------------------------------------------------------
-- route_analytics
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS route_analytics (
    id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    route_id             UUID,
    origin_country       TEXT,
    dest_country         TEXT,
    avg_duration_hours   NUMERIC(8,2),
    avg_distance_km      NUMERIC(10,3),
    success_rate_pct     NUMERIC(5,2),
    trip_count           INT         DEFAULT 0,
    period_start         DATE,
    period_end           DATE,
    calculated_at        TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE route_analytics IS 'Aggregated performance analytics for origin-to-destination route corridors';
COMMENT ON COLUMN route_analytics.route_id           IS 'Optional cross-DB reference to routes.id in kinara_transport';
COMMENT ON COLUMN route_analytics.origin_country     IS 'ISO country code of the route origin';
COMMENT ON COLUMN route_analytics.dest_country       IS 'ISO country code of the route destination';
COMMENT ON COLUMN route_analytics.avg_duration_hours IS 'Mean transit duration in hours across all trips in the period';
COMMENT ON COLUMN route_analytics.avg_distance_km    IS 'Mean route distance in kilometres';
COMMENT ON COLUMN route_analytics.success_rate_pct   IS 'Percentage of trips on this route that were successfully delivered';
COMMENT ON COLUMN route_analytics.trip_count         IS 'Total number of trips used to compute these aggregates';
COMMENT ON COLUMN route_analytics.period_start       IS 'First date of the analytics aggregation window';
COMMENT ON COLUMN route_analytics.period_end         IS 'Last date of the analytics aggregation window';

-- ---------------------------------------------------------------------------
-- logistics_analytics_audit_log  (immutable)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS logistics_analytics_audit_log (
    id             BIGSERIAL    PRIMARY KEY,
    entity_id      UUID         NOT NULL,
    action         TEXT         NOT NULL,
    actor_id       TEXT         NOT NULL,
    old_data       JSONB,
    new_data       JSONB,
    signature_hash TEXT,
    ip_address     INET,
    occurred_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE logistics_analytics_audit_log IS 'Immutable audit trail for all logistics-analytics-service mutations';

CREATE RULE no_update_la_audit AS ON UPDATE TO logistics_analytics_audit_log DO INSTEAD NOTHING;
CREATE RULE no_delete_la_audit AS ON DELETE TO logistics_analytics_audit_log DO INSTEAD NOTHING;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_delivery_metrics_date_country  ON delivery_metrics(metric_date, country);
CREATE INDEX IF NOT EXISTS idx_vehicle_util_vehicle_date      ON vehicle_utilization(vehicle_id, metric_date);
CREATE INDEX IF NOT EXISTS idx_route_analytics_corridor_period ON route_analytics(origin_country, dest_country, period_start);
CREATE INDEX IF NOT EXISTS idx_la_audit_entity                ON logistics_analytics_audit_log(entity_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_la_audit_actor                 ON logistics_analytics_audit_log(actor_id, occurred_at);

-- =============================================================================
-- DOWN (rollback)
-- DROP INDEX IF EXISTS idx_la_audit_actor;
-- DROP INDEX IF EXISTS idx_la_audit_entity;
-- DROP INDEX IF EXISTS idx_route_analytics_corridor_period;
-- DROP INDEX IF EXISTS idx_vehicle_util_vehicle_date;
-- DROP INDEX IF EXISTS idx_delivery_metrics_date_country;
-- DROP RULE IF EXISTS no_delete_la_audit ON logistics_analytics_audit_log;
-- DROP RULE IF EXISTS no_update_la_audit ON logistics_analytics_audit_log;
-- DROP TABLE IF EXISTS logistics_analytics_audit_log;
-- DROP TABLE IF EXISTS route_analytics;
-- DROP TABLE IF EXISTS vehicle_utilization;
-- DROP TABLE IF EXISTS delivery_metrics;
-- =============================================================================
