package handlers_test

// Cross-tenant isolation suite for the shared scaffold handler.
//
// The scaffold handler package is generated byte-for-byte identical across the
// ~100 pillar services, so this suite proves the isolation property for that
// shared code path rather than one service's private copy. It is generated into
// every scaffold service by scripts/gen_scaffold_tests.py.
//
// Every case runs in BOTH TENANT_SCOPE_MODE values:
//   - report:  gateway RequireTenantScope only logs would-be blocks (entity_type /
//              clinic checks). It must NOT relax row-level tenant scoping.
//   - enforce: gateway returns 403 on entity_type/clinic violations.
//
// Row-level scoping lives entirely in the handler (TenantID filtering in
// List/Get/Delete) and is independent of the mode. If tenant A can reach tenant
// B's rows in EITHER mode, that is a critical finding.

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/klinova/kinara-os/population-health-service/db"
)

var isolationModes = []string{"report", "enforce"}

// seedRecord appends a record owned by the given tenant directly to the store,
// bypassing HTTP so the seed itself cannot be affected by scoping.
func seedRecord(store *mockQuerier, id, tenant uuid.UUID, enc string) {
	store.mu.Lock()
	defer store.mu.Unlock()
	store.records = append(store.records, db.Record{
		ID:        id,
		DataEnc:   enc,
		TenantID:  tenant,
		CreatedBy: uuid.New(),
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	})
}

// Test 1 — list endpoint scoping.
func TestIsolation_List(t *testing.T) {
	for _, mode := range isolationModes {
		t.Run(mode, func(t *testing.T) {
			t.Setenv("TENANT_SCOPE_MODE", mode)
			store := &mockQuerier{}
			tenantA, tenantB := uuid.New(), uuid.New()
			idA, idB := uuid.New(), uuid.New()
			seedRecord(store, idA, tenantA, "enc-A")
			seedRecord(store, idB, tenantB, "enc-B")

			srv := newTestServer(t, store)
			defer srv.Close()

			req, _ := http.NewRequest(http.MethodGet, srv.URL+"/api/v1/population-healths", nil)
			req.Header.Set("Authorization", "Bearer "+mintToken(t, "klinova", tenantA))
			resp, err := http.DefaultClient.Do(req)
			if err != nil {
				t.Fatal(err)
			}
			defer resp.Body.Close()
			raw, _ := io.ReadAll(resp.Body)

			if resp.StatusCode != http.StatusOK {
				t.Fatalf("[%s] list want 200, got %d", mode, resp.StatusCode)
			}

			var body struct {
				Items []map[string]interface{} `json:"items"`
			}
			if err := json.Unmarshal(raw, &body); err != nil {
				t.Fatalf("[%s] decode: %v", mode, err)
			}

			if len(body.Items) != 1 {
				t.Errorf("[%s] tenantA must see exactly 1 record, got %d", mode, len(body.Items))
			}
			// The strongest check: tenantB's id must not appear ANYWHERE in the body.
			if strings.Contains(string(raw), idB.String()) {
				t.Errorf("[%s] CRITICAL: tenantB record id %s leaked into tenantA's list body", mode, idB)
			}
			if len(body.Items) == 1 {
				if got, _ := body.Items[0]["id"].(string); got != idA.String() {
					t.Errorf("[%s] listed id = %s, want tenantA's %s", mode, got, idA)
				}
			}
			t.Logf("[%s] list: %d item(s) returned; tenantB id in body = %v",
				mode, len(body.Items), strings.Contains(string(raw), idB.String()))
		})
	}
}

// Test 2 — read-by-id across tenants. Reports the actual status; 404 preferred
// over 403 (403 confirms the record exists, leaking existence to a prober).
func TestIsolation_ReadByID(t *testing.T) {
	for _, mode := range isolationModes {
		t.Run(mode, func(t *testing.T) {
			t.Setenv("TENANT_SCOPE_MODE", mode)
			store := &mockQuerier{}
			tenantA, tenantB := uuid.New(), uuid.New()
			idB := uuid.New()
			seedRecord(store, idB, tenantB, "enc-B")

			srv := newTestServer(t, store)
			defer srv.Close()

			req, _ := http.NewRequest(http.MethodGet, srv.URL+"/api/v1/population-healths/"+idB.String(), nil)
			req.Header.Set("Authorization", "Bearer "+mintToken(t, "klinova", tenantA))
			resp, err := http.DefaultClient.Do(req)
			if err != nil {
				t.Fatal(err)
			}
			resp.Body.Close()

			t.Logf("[%s] cross-tenant GET by id returned: %d", mode, resp.StatusCode)
			switch resp.StatusCode {
			case http.StatusOK:
				t.Errorf("[%s] CRITICAL: tenantA read tenantB's record (200)", mode)
			case http.StatusNotFound:
				// preferred — does not confirm the record exists
			case http.StatusForbidden:
				t.Errorf("[%s] cross-tenant GET returned 403 — leaks existence of tenantB's record; 404 preferred", mode)
			default:
				t.Errorf("[%s] cross-tenant GET returned %d — want 404", mode, resp.StatusCode)
			}
		})
	}
}

// Test 3 — write path. A create body carrying tenantB's id must not override the
// tenant taken from the JWT.
func TestIsolation_WriteOverride(t *testing.T) {
	for _, mode := range isolationModes {
		t.Run(mode, func(t *testing.T) {
			t.Setenv("TENANT_SCOPE_MODE", mode)
			store := &mockQuerier{}
			tenantA, tenantB := uuid.New(), uuid.New()

			srv := newTestServer(t, store)
			defer srv.Close()

			body := `{"name":"smuggle","tenant_id":"` + tenantB.String() + `"}`
			req, _ := http.NewRequest(http.MethodPost, srv.URL+"/api/v1/population-healths", bytes.NewBufferString(body))
			req.Header.Set("Authorization", "Bearer "+mintToken(t, "klinova", tenantA))
			req.Header.Set("Content-Type", "application/json")
			resp, err := http.DefaultClient.Do(req)
			if err != nil {
				t.Fatal(err)
			}
			resp.Body.Close()
			if resp.StatusCode != http.StatusCreated {
				t.Fatalf("[%s] create want 201, got %d", mode, resp.StatusCode)
			}

			store.mu.Lock()
			defer store.mu.Unlock()
			if len(store.records) != 1 {
				t.Fatalf("[%s] want 1 stored record, got %d", mode, len(store.records))
			}
			got := store.records[0].TenantID
			switch got {
			case tenantB:
				t.Errorf("[%s] CRITICAL: body tenant_id overrode the JWT — record stored under tenantB", mode)
			case tenantA:
				// correct
			default:
				t.Errorf("[%s] stored TenantID = %s, want tenantA %s", mode, got, tenantA)
			}
			t.Logf("[%s] stored TenantID = %s (tenantA=%s, tenantB=%s)", mode, got, tenantA, tenantB)
		})
	}
}

// Test 4 — update and delete across tenants. The security property is that
// tenantB's record survives unchanged. Status codes are reported and flagged.
func TestIsolation_UpdateDelete(t *testing.T) {
	for _, mode := range isolationModes {
		t.Run(mode, func(t *testing.T) {
			t.Setenv("TENANT_SCOPE_MODE", mode)
			store := &mockQuerier{}
			tenantA, tenantB := uuid.New(), uuid.New()
			idB := uuid.New()
			const origEnc = "enc-B-original"
			seedRecord(store, idB, tenantB, origEnc)

			srv := newTestServer(t, store)
			defer srv.Close()
			tokA := "Bearer " + mintToken(t, "klinova", tenantA)

			// UPDATE tenantB's record as tenantA.
			upReq, _ := http.NewRequest(http.MethodPut, srv.URL+"/api/v1/population-healths/"+idB.String(),
				bytes.NewBufferString(`{"name":"hijacked"}`))
			upReq.Header.Set("Authorization", tokA)
			upReq.Header.Set("Content-Type", "application/json")
			upResp, err := http.DefaultClient.Do(upReq)
			if err != nil {
				t.Fatal(err)
			}
			upResp.Body.Close()
			t.Logf("[%s] cross-tenant PUT returned: %d", mode, upResp.StatusCode)
			if upResp.StatusCode >= 200 && upResp.StatusCode < 300 {
				// Not a data breach (see integrity check below), but the endpoint
				// reports success on another tenant's id. For the scaffold this is
				// the unimplemented update stub: no ownership check, no mutation.
				t.Logf("[%s] FLAG: PUT on tenantB's id returned success %d without an ownership check (scaffold update is a stub)", mode, upResp.StatusCode)
			}

			// DELETE tenantB's record as tenantA.
			delReq, _ := http.NewRequest(http.MethodDelete, srv.URL+"/api/v1/population-healths/"+idB.String(), nil)
			delReq.Header.Set("Authorization", tokA)
			delResp, err := http.DefaultClient.Do(delReq)
			if err != nil {
				t.Fatal(err)
			}
			delResp.Body.Close()
			t.Logf("[%s] cross-tenant DELETE returned: %d", mode, delResp.StatusCode)

			// The property that must hold: tenantB's record is unchanged.
			store.mu.Lock()
			defer store.mu.Unlock()
			var found *db.Record
			for i := range store.records {
				if store.records[i].ID == idB {
					found = &store.records[i]
					break
				}
			}
			if found == nil {
				t.Fatalf("[%s] CRITICAL: tenantA deleted tenantB's record", mode)
			}
			if found.TenantID != tenantB {
				t.Errorf("[%s] CRITICAL: tenantB record TenantID changed to %s", mode, found.TenantID)
			}
			if found.DataEnc != origEnc {
				t.Errorf("[%s] CRITICAL: tenantB record content mutated: %q != %q", mode, found.DataEnc, origEnc)
			}
		})
	}
}
