#!/usr/bin/env python3
"""
Kinara OS — DigitalOcean PostgreSQL Provisioner

Creates the managed PostgreSQL cluster, polls until active, and writes
the connection string to .env.prod.

Usage:
    export DO_API_TOKEN=<token-from-DO-dashboard>
    python3 infrastructure/scripts/provision.py [--dry-run]
"""
import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request

DO_API = "https://api.digitalocean.com/v2"
DB_SPEC = {
    "name": "kinara-prod-db",
    "engine": "pg",
    "version": "15",
    "region": "fra1",
    "size": "db-s-4vcpu-8gb",
    "num_nodes": 2,
    "tags": ["kinara", "production"],
}
POLL_INTERVAL = 30  # seconds
POLL_TIMEOUT = 1800  # 30 minutes


def api(method, path, body=None, token=None):
    url = f"{DO_API}{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(
        url, data=data, method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"[error] {method} {path} → {e.code}: {body}", file=sys.stderr)
        sys.exit(1)


def wait_for_active(cluster_id, token):
    deadline = time.time() + POLL_TIMEOUT
    while time.time() < deadline:
        data = api("GET", f"/databases/{cluster_id}", token=token)
        status = data["database"]["status"]
        print(f"  [poll] status: {status}")
        if status == "online":
            return data["database"]
        time.sleep(POLL_INTERVAL)
    print("[error] timed out waiting for database to come online", file=sys.stderr)
    sys.exit(1)


def write_env(db, outfile=".env.prod"):
    conn = db["connection"]
    lines = [
        "# Kinara OS — Production DB credentials (generated by provision.py)",
        f'DB_HOST={conn["host"]}',
        f'DB_PORT={conn["port"]}',
        f'DB_USER={conn["user"]}',
        f'DB_PASSWORD={conn["password"]}',
        f'DB_NAME={conn["database"]}',
        f'DATABASE_URL=postgresql://{conn["user"]}:{conn["password"]}@{conn["host"]}:{conn["port"]}/{conn["database"]}?sslmode=require',
        "",
        "# Set these after running infrastructure/database/scripts/create_db_users.sql",
        "APP_USER_PASSWORD=",
        "READ_ONLY_PASSWORD=",
        "BACKUP_USER_PASSWORD=",
    ]
    with open(outfile, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[done] credentials written to {outfile}")
    print(f"[warn] {outfile} contains secrets — never commit this file")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--env-out", default=".env.prod")
    args = parser.parse_args()

    token = os.environ.get("DO_API_TOKEN")
    if not token:
        print("[error] DO_API_TOKEN env var is required", file=sys.stderr)
        sys.exit(1)

    print("╔══════════════════════════════════════════════════════════╗")
    print("║   Kinara OS — DigitalOcean PostgreSQL Provisioner       ║")
    print("╚══════════════════════════════════════════════════════════╝")
    print(f"  spec: {DB_SPEC['name']} / {DB_SPEC['region']} / {DB_SPEC['size']}")

    if args.dry_run:
        print("  [dry-run] would POST /v2/databases — skipping")
        return

    # Check if cluster already exists
    existing = api("GET", "/databases", token=token)
    for db in existing.get("databases", []):
        if db["name"] == DB_SPEC["name"]:
            cluster_id = db["id"]
            print(f"  [found] existing cluster {cluster_id} status={db['status']}")
            if db["status"] != "online":
                print("  [wait] polling until online …")
                db = wait_for_active(cluster_id, token)
            write_env(db, args.env_out)
            return

    # Create cluster
    print("  [create] provisioning new cluster …")
    result = api("POST", "/databases", body=DB_SPEC, token=token)
    cluster_id = result["database"]["id"]
    print(f"  [created] cluster_id={cluster_id}")

    print("  [wait] polling until online …")
    db = wait_for_active(cluster_id, token)

    write_env(db, args.env_out)

    print("")
    print("  Next steps:")
    print("  1. psql $DATABASE_URL -f infrastructure/database/scripts/create_db_users.sql")
    print("  2. ./infrastructure/scripts/run-migrations.sh")
    print("  3. ./infrastructure/scripts/verify-db.sh")


if __name__ == "__main__":
    main()
