-- 50 test clinics in Togo across 5 regions
\c kinara_patient;

INSERT INTO clinics (id, name, phone, address, region, country, clinic_type, capacity_beds, is_active, tenant_id, created_at)
VALUES
  (gen_random_uuid(), 'Centre de Santé de Lomé-Nord',     '+22890001001', '12 Rue des Cliniques, Lomé',        'Maritime',  'TG', 'health_center', 30, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital de District de Tsévié',    '+22890001002', '5 Avenue de la Santé, Tsévié',      'Maritime',  'TG', 'district',      80, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre Médical de Kpalimé',        '+22890001003', '23 Rue du Commerce, Kpalimé',       'Plateaux',  'TG', 'health_center', 25, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital Préfectoral de Sokodé',    '+22890001004', '8 Boulevard Central, Sokodé',       'Centrale',  'TG', 'prefectoral',  120, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Kara',          '+22890001005', '45 Rue de l''Hôpital, Kara',        'Kara',      'TG', 'regional',     200, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire de Vogan',             '+22890001006', '3 Place du Marché, Vogan',          'Maritime',  'TG', 'dispensary',    10, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé d''Aného',         '+22890001007', '7 Rue de la Mer, Aného',            'Maritime',  'TG', 'health_center', 20, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital de District d''Atakpamé',  '+22890001008', '15 Avenue de la République',        'Plateaux',  'TG', 'district',      60, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre Médical de Badou',          '+22890001009', '2 Rue Principale, Badou',           'Plateaux',  'TG', 'health_center', 18, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire de Notse',             '+22890001010', '9 Rue du Dispensaire, Notsé',       'Plateaux',  'TG', 'dispensary',    12, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Tchamba',       '+22890001011', '6 Rue de la Santé, Tchamba',        'Centrale',  'TG', 'health_center', 22, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital Régional de Sokodé',       '+22890001012', '1 Boulevard du Nord, Sokodé',       'Centrale',  'TG', 'regional',     150, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Bassar',        '+22890001013', '14 Rue Bassar, Bassar',             'Centrale',  'TG', 'health_center', 16, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Bafilo',        '+22890001014', '11 Avenue Centrale, Bafilo',        'Kara',      'TG', 'health_center', 20, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire de Niamtougou',        '+22890001015', '4 Rue du Village, Niamtougou',      'Kara',      'TG', 'dispensary',     8, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital de District de Kara',      '+22890001016', '22 Avenue de l''Hôpital, Kara',     'Kara',      'TG', 'district',      90, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Pagouda',       '+22890001017', '5 Rue Principale, Pagouda',         'Kara',      'TG', 'health_center', 14, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Kandé',         '+22890001018', '8 Rue du Marché, Kandé',            'Kara',      'TG', 'health_center', 12, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital Régional de Dapaong',      '+22890001019', '3 Boulevard Principal, Dapaong',    'Savanes',   'TG', 'regional',     180, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Tone',          '+22890001020', '17 Rue de Tone, Dapaong',           'Savanes',   'TG', 'health_center', 20, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire de Mandouri',          '+22890001021', '1 Rue du Dispensaire, Mandouri',    'Savanes',   'TG', 'dispensary',     6, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Cinkassé',      '+22890001022', '9 Avenue Principale, Cinkassé',     'Savanes',   'TG', 'health_center', 15, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Tandjouaré',    '+22890001023', '6 Rue de la Santé, Tandjouaré',     'Savanes',   'TG', 'health_center', 14, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital de District de Lomé-Sud',  '+22890001024', '30 Boulevard du Littoral, Lomé',    'Maritime',  'TG', 'district',      70, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Zio',           '+22890001025', '12 Rue Zio, Tsévié',               'Maritime',  'TG', 'health_center', 18, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre Médical CHU Lomé',          '+22890001026', '1 Avenue CHU, Lomé',                'Maritime',  'TG', 'teaching',     400, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Kloto',         '+22890001027', '8 Rue de Kloto, Kpalimé',          'Plateaux',  'TG', 'health_center', 20, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire d''Agou',              '+22890001028', '3 Rue d''Agou, Agou',               'Plateaux',  'TG', 'dispensary',    10, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Wawa',          '+22890001029', '7 Rue de Wawa, Badou',              'Plateaux',  'TG', 'health_center', 16, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Danyi',         '+22890001030', '5 Avenue Danyi, Kpalimé',          'Plateaux',  'TG', 'health_center', 14, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital de District d''Amou',      '+22890001031', '19 Rue de l''Amou, Atakpamé',       'Plateaux',  'TG', 'district',      55, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Haho',          '+22890001032', '4 Rue Haho, Notsé',                 'Plateaux',  'TG', 'health_center', 12, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire de Moyen-Mono',        '+22890001033', '2 Rue du Mono, Atakpamé',           'Plateaux',  'TG', 'dispensary',     8, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé d''Anié',          '+22890001034', '11 Avenue d''Anié, Anié',           'Plateaux',  'TG', 'health_center', 18, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital de District de Tchamba',   '+22890001035', '7 Rue de Tchamba, Tchamba',         'Centrale',  'TG', 'district',      65, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Blitta',        '+22890001036', '3 Rue de Blitta, Blitta',           'Centrale',  'TG', 'health_center', 16, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire de Sotouboua',         '+22890001037', '8 Rue Principale, Sotouboua',       'Centrale',  'TG', 'dispensary',    10, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Dankpen',       '+22890001038', '6 Rue de Dankpen, Kara',            'Kara',      'TG', 'health_center', 14, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Keran',         '+22890001039', '4 Avenue Principale, Bafilo',       'Kara',      'TG', 'health_center', 12, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire de Binah',             '+22890001040', '1 Rue de Binah, Pagouda',           'Kara',      'TG', 'dispensary',     8, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé d''Oti',           '+22890001041', '9 Rue d''Oti, Mango',               'Savanes',   'TG', 'health_center', 20, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital de District de Mango',     '+22890001042', '15 Avenue de Mango, Mango',         'Savanes',   'TG', 'district',      75, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Kpendjal',      '+22890001043', '7 Rue de Kpendjal, Dapaong',        'Savanes',   'TG', 'health_center', 16, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire de Tône-Est',          '+22890001044', '3 Rue de Tône-Est, Dapaong',        'Savanes',   'TG', 'dispensary',     8, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre Médical de Bè',             '+22890001045', '44 Route de Bè, Lomé',              'Maritime',  'TG', 'health_center', 22, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé d''Agoè',          '+22890001046', '18 Rue d''Agoè, Lomé',             'Maritime',  'TG', 'health_center', 25, true, 'TG', NOW()),
  (gen_random_uuid(), 'Dispensaire de Yoto',              '+22890001047', '5 Rue Yoto, Tabligbo',              'Maritime',  'TG', 'dispensary',    10, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Golfe',         '+22890001048', '22 Boulevard du Golfe, Lomé',       'Maritime',  'TG', 'health_center', 28, true, 'TG', NOW()),
  (gen_random_uuid(), 'Centre de Santé de Vo',            '+22890001049', '6 Rue de Vo, Vogan',                'Maritime',  'TG', 'health_center', 18, true, 'TG', NOW()),
  (gen_random_uuid(), 'Hôpital de Référence de Lomé',     '+22890001050', '100 Boulevard de la République',    'Maritime',  'TG', 'reference',    300, true, 'TG', NOW())
ON CONFLICT DO NOTHING;
